version: "3"

services:
    db:
        image: postgres
    api:
        build: ./api
        volumes:
            - ./socket:/socket
        depends_on:
            - db
    nginx:
        build: ./nginx
        volumes:
            - ./socket:/socket
            - ./api:/api
        depends_on:
            - api
        ports:
            - "8000:80"
